// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/.well-known/nodeinfo.ts";
import * as $1 from "./routes/.well-known/webfinger.ts";
import * as $2 from "./routes/[name].tsx";
import * as $3 from "./routes/_404.tsx";
import * as $4 from "./routes/_middleware.ts";
import * as $5 from "./routes/api/_middleware.ts";
import * as $6 from "./routes/api/v1/accounts/[acct]/index.ts";
import * as $7 from "./routes/api/v1/accounts/[acct]/statuses.ts";
import * as $8 from "./routes/api/v1/instance.ts";
import * as $9 from "./routes/api/v1/statuses/[id]/index.ts";
import * as $10 from "./routes/api/v1/timelines/public.ts";
import * as $11 from "./routes/index.tsx";
import * as $12 from "./routes/nodeinfo/2.0.ts";
import * as $13 from "./routes/toot/[id].tsx";
import * as $14 from "./routes/users/[name]/followers.ts";
import * as $15 from "./routes/users/[name]/following.ts";
import * as $16 from "./routes/users/[name]/inbox.ts";
import * as $17 from "./routes/users/[name]/index.ts";
import * as $18 from "./routes/users/[name]/outbox.ts";
import * as $19 from "./routes/users/[name]/statuses/[id]/activity.ts";
import * as $20 from "./routes/users/[name]/statuses/[id]/index.ts";
import * as $21 from "./routes/users/_middleware.ts";

const manifest = {
  routes: {
    "./routes/.well-known/nodeinfo.ts": $0,
    "./routes/.well-known/webfinger.ts": $1,
    "./routes/[name].tsx": $2,
    "./routes/_404.tsx": $3,
    "./routes/_middleware.ts": $4,
    "./routes/api/_middleware.ts": $5,
    "./routes/api/v1/accounts/[acct]/index.ts": $6,
    "./routes/api/v1/accounts/[acct]/statuses.ts": $7,
    "./routes/api/v1/instance.ts": $8,
    "./routes/api/v1/statuses/[id]/index.ts": $9,
    "./routes/api/v1/timelines/public.ts": $10,
    "./routes/index.tsx": $11,
    "./routes/nodeinfo/2.0.ts": $12,
    "./routes/toot/[id].tsx": $13,
    "./routes/users/[name]/followers.ts": $14,
    "./routes/users/[name]/following.ts": $15,
    "./routes/users/[name]/inbox.ts": $16,
    "./routes/users/[name]/index.ts": $17,
    "./routes/users/[name]/outbox.ts": $18,
    "./routes/users/[name]/statuses/[id]/activity.ts": $19,
    "./routes/users/[name]/statuses/[id]/index.ts": $20,
    "./routes/users/_middleware.ts": $21,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
